title: Solar Powered Raspberry Pi Pico
hero_image: images/banner.png
description: Power a Raspberry Pi Pico with solar energy
listed: false
pdf: false
steps:
  - title: Solar powered Raspberry Pi Pico
    completion:
      - engaged
      - internal
      - external
